### ISSUE TITLE
Dropbox

### ISSUE THREAD

**Issue by RichardJones74** [sprang/Inkpad#156] opened 2016-02-18 00:58 UTC
Dropbox is not working

**Comment by alistairmcmillan** [comment] 2016-02-18 00:59
Which version of InkPad do you have installed?

**Comment by RichardJones74** [comment] 2016-02-18 01:30
@alistairmcmillan I have the Taprix one. I have reached out to Envoza before and I got some information about him and his app. If you want it just let me know.

**Comment by alistairmcmillan** [comment] 2016-02-18 01:40
Dropbox changed things about a wee bit so the Dropbox support in the last Taptrix release won't work anymore.

Thanks for mentioning the Envoza release. I'll add it to the list. Do you know if they have published their code changes anywhere (as required by the license)?

**Comment by RichardJones74** [comment] 2016-02-18 01:44
Envoza has no source code. I have asked him about it. He admitted to it.

**Comment by alistairmcmillan** [comment] 2016-02-18 01:46
Did he say if he had any plans to release it?

**Comment by RichardJones74** [comment] 2016-02-18 01:49
When I asked him about it he avoided the entire subject so would assume no.

**Comment by alistairmcmillan** [comment] 2016-02-18 10:20
Duplicate of #150

**Closed as completed by alistairmcmillan** 2016-02-18 10:20 UTC
Labels: duplicate

**Comment by michaeldugan** [comment] 2016-02-19 19:52
@alistairmcmillan I published the files to Github on a new repository using the instructions you gave me and the desktop app. How long does it take for the files to upload?

**Comment by michaeldugan** [comment] 2016-02-19 20:17
I am having some trouble can you help me?

**Comment by alistairmcmillan** [comment] 2016-02-20 10:57
What are you having trouble with?

**Comment by michaeldugan** [comment] 2016-02-20 14:19
For some reason when I hit publish nothing happens

**Comment by alistairmcmillan** [comment] 2016-02-22 00:12
@RichardJones74 Could you email me at alistairmcmillan75@gmail.com please?

**Comment by RichardJones74** [comment] 2016-02-22 00:21
@alistairmcmillan I have just emailed you we can discuss there now

**Comment by michaeldugan** [comment] 2016-02-22 00:43
@alistairmcmillan Can you help me I don't know what I am doing that the Desktop app won't upload my source.

**Comment by alistairmcmillan** [comment] 2016-02-22 01:04
Email me at alistairmcmillan75@gmail.com and I'll see if I can help.

**Comment by alistairmcmillan** [comment] 2016-02-22 01:06
@michaeldugan Email me at alistairmcmillan75@gmail.com and I'll see if I can help.
