### ISSUE TITLE
View alignment in popovers under iOS8

### ISSUE THREAD

**Issue by mrtally** [sprang/Inkpad#133] opened 2014-09-23 04:39 UTC
View alignment in popovers under iOS8

![img_0143](https://cloud.githubusercontent.com/assets/7572630/4367517/7270ae1c-42d9-11e4-99af-e79867c43888.PNG)

**Comment by alistairmcmillan** [comment] 2014-10-04 16:15
I'm assuming this is about the red slider being under the header. When I try this on my first gen iPad mini I don't get that. Everything is aligned okay. Can you still recreate this problem? And if so which version of iOS and which iPad are you currently using?

**Comment by CuSoft** [comment] 2014-10-04 18:19
I first noticed this myself in iOS 8. 7 did not include the issue, very interestingly.

Seems to be 64-bit related? Try the Air or mini 2, which are the first 64-bit hardware in the Apple line, I believe.

**Comment by alistairmcmillan** [comment] 2014-10-04 18:20
And you still get that misaligned control?

**Comment by CuSoft** [comment] 2014-10-04 18:23
I believe the original mini was a mirror of the iPad 2 system, which is a 32-bit hardware system, so it runs the 32-bit iteration of any iOS system firmware and software, including iOS 7 and 8 which were the first to have 64-bit versions. This seems to be the issue. If inkpad is run in 64-bit retina xcode software emulation, the issue is easily reproduced as well.

Yes, 8.0.0 introduced the issue and 8.0.2 still includes the problem. This may be fixed with a future revision of the Apple iOS itself, however I can not seem to find duplicate identical issues across various forums. Looks like "mrtally" also saw the issue, as the thread was opened by him.

I have time today to look into potential fixes as well if you have any ideas.

**Comment by alistairmcmillan** [comment] 2014-10-04 19:10
Interesting but I tried taking out the arm64 architecture in Build Settings and built & ran Inkpad in the simulator. So it's running now as a 32 bit app (confirmed by Activity Monitor) but still has that misalignment though.

**Comment by alistairmcmillan** [comment] 2014-10-04 19:27
Which version of Inkpad are you running? Have you compiled your own version or are you running the latest version from the app store?

**Comment by CuSoft** [comment] 2014-10-04 20:01
I am running the taptrix version from the App Store icon on my mini 2 running 8.0.2. Should I attempt another version?

**Comment by CuSoft** [comment] 2014-10-04 20:35
...what I should have done a week ago was download and test new builds of iOS instead of doing the work on the inkpad side.

I downloaded a version of iOS 8 that will likely be pushed next (8.0.3?) and will likely go gold soon? It DOES fix the issue I am having, so apparently this was a bug in the OS system and not inkpad's 64-bit code.

I would recommend closure of this topic as the newest update will rectify the issue automatically and re-creating might not be the best use of time. Thank you for yours though.

**Comment by alistairmcmillan** [comment] 2014-10-04 20:40
Good to hear. I'm assuming you mean 8.1? Funny thing is if I download the current version of Inkpad from the App Store onto my 1st gen mini running 8.0.2 I don't have the problem. However if I compile the current code from GitHub and install it onto the same device I do have the problem. So I don't think this is anything to do with 32/64 bit. So this is a little strange. I guess we should leave the call open until 8.1 is out and everyone can confirm it fixes the issue.

**Comment by CuSoft** [comment] 2014-10-04 20:42
I like the way you think. I have been perplexed over this as no one else seems to be dealing with this exact issue with iOS 8! Have a great weekend.

P.S. I take back what I said about the 32 bit/ 64 bit issue. Your idea makes more sense to me than some ethereal amd64 bit issue, which is what I have been dealing with on another project. Thanks again.

**Comment by CuSoft** [comment] 2014-10-15 02:32
navController.navigationBar.translucent is being set to YES in iOS8.

That's the issue. If we force 

navController.navigationBar.translucent = NO;

into EACH AND EVERY one of the "show" modules of the wdcanvascontroller class, this issue is fixed. This way we know if Apple every alters their default plist again for the total iOS 9 system, this issue does not come back.

**Comment by ghost** [comment] 2014-10-31 20:22
CuSoft, 
navController.navigationBar.translucent is being set to YES in iOS8

Where is this located? or where can I make these changes?

**Comment by CuSoft** [comment] 2014-11-04 13:54
Can I request to become a collaborator on the project and offer a commit myself? WDCanvasController.m has a series of "show" functions that are no longer iOS8 compatible. I can offer a working commit myself, if possible?

The declaration of the UINavigationController in the show function is no longer iOS8 compatible without new defining graphic options. I have it working here. Let me know what is easier and thanks again.

**Comment by alistairmcmillan** [comment] 2014-11-04 14:51
Why not just fork and submit a pull request?

https://help.github.com/articles/fork-a-repo/

Your pull request will even appear in this thread if you mention "#133" in the pull request. :)

**Comment by CuSoft** [comment] 2014-11-04 14:56
Go light on me. I'm new! Alright, we'll do this your way.

**Comment by alistairmcmillan** [comment] 2014-11-04 15:02
:) Any problems, give us a shout. alistairmcmillan75@gmail.com

**Comment by temmink** [comment] 2015-11-10 23:04
I'm on ios 9.1 with Ipad 3 (retina) and still have this issue
Btw. App store version.

**Comment by temmink** [comment] 2015-11-10 23:27
I have downloaded the git-version and tried that one.
But same problem.

How can I solve this?

**Comment by temmink** [comment] 2015-11-10 23:35
Okay, managed to solve the problem by implementing the fix for issue #133 as mentioned by mpprdev.

**Comment by ghost** [comment] 2016-02-08 02:20
Can this be merged?

**Comment by alistairmcmillan** [comment] 2016-02-11 23:28
Merged fix for this issue.

**Closed as completed by alistairmcmillan** 2016-02-11 23:28 UTC
Labels: bug
