### ISSUE TITLE
Feature request: rotate: view and/or enter precise angle

### ISSUE THREAD

**Issue by KrisDJ** [sprang/Inkpad#122] opened 2014-05-05 19:19 UTC
When rotating an object, I would want to see the angle at which the object is rotated, and/or enter an angle at which to rotate.

**Comment by jimbox13** [comment] 2014-05-08 16:50
I'd love this too.

**Comment by alistairmcmillan** [comment] 2014-10-08 15:48
Duplicate of #114

**Closed as completed by alistairmcmillan** 2014-10-08 15:48 UTC
Labels: duplicate, enhancement
