### ISSUE TITLE
Bluetooth pen options

### ISSUE THREAD

**Issue by alexasue** [sprang/Inkpad#50] opened 2013-12-16 00:03 UTC
I love this app. It's the one of the best vector drawing apps out there. I use the pen tool and I love the option of a type on a path tool. I wish you could make this app full screen when working. What I believe would make it even better is to add support for the wacom intuos creative stylus, and/or pogo connect.

**Comment by sprang** [comment] 2013-12-16 19:26
It's a fair amount of trouble to add support for third party hardware for not much payoff (Inkpad doesn't currently use any pressure data). I might reconsider this option in the future. Duplicate of Issue #27.

**Closed as completed by sprang** 2013-12-16 19:26 UTC
Labels: duplicate
